swagger: "2.0"
info:
  title: IP Blocklist Service
  description: API to check if an IP belongs to a blocklist
  version: 1.0.0
host: localhost:8000
basePath: /api
schemes:
  - http
paths:
  /ips/{ipv4}:
    get:
      tags:
        - ipv4
      summary: Get IP status
      description: Returns IP status
      operationId: getIpStatus
      parameters:
        - name: ipv4
          in: path
          description: IP to test against
          example: 192.168.0.1
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ipv4Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Ipv4Response'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
            application/xml:
              schema:
                $ref: '#/components/schemas/APIError'
        '404':
          description: Service not found

components:
  schemas:
    APIError:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: The request failed while waiting for another service
        trace:
          type: string
          descriptiont: Error stack trace
          example: line 26 - Can not decompress None
      xml:
        name: ipv4
    Ipv4Response:
      type: object
      properties:
        is_blocked:
          type: boolean
          example: false
      xml:
        name: ipv4